language: cpp

cache: pip

before_install:
  - mkdir build && cd build
  - which $CXX
  - which $CC
  - $CXX --version

install:
  - pip install --user conan
  - conan install ..

script:
  - conan build ..
